name: MAV
description: No longer testing..
title: Is this a blog?

url: http://blog.m-a-v.dk
    #http://blog.m-a-v.dk
    #http://localhost:1337
markdown: kramdown
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
safe: true
permalink: /:year/:month/:day/:title 
author: 'Mikkel Vej'
email: blog@m-a-v.dk
paginate: 3 # Max amount of post displayed per page

disqus:
    shortname: 'M-AV'

excerpt_separator: "<!--more-->"

min_width: '300px'

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      is_post: "true"
