name: MAV
description: Still testing
title: Is this a blog?

url: http://m-av.github.io
    #file:///E:/Projects/GitHub_Website/M-AV.github.io/_site 
    #http://m-av.github.io
markdown: redcarpet
highlighter: pygments
safe: true
permalink: pretty
author: 'Mikkel Vej'
email: blog@m-a-v.dk

disqus:
    shortname: 'M-AV'

excerpt_separator: "<!--more-->"