name: MAV
description: Still testing
title: Is this a blog?

url: http://blog.m-a-v.dk
    #file:///E:/Projects/GitHub_Website/M-AV.github.io/_site
    #http://blog.m-a-v.dk
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
safe: true
permalink: pretty
author: 'Mikkel Vej'
email: blog@m-a-v.dk

disqus:
    shortname: 'M-AV'

excerpt_separator: "<!--more-->"